; generated by SuperSlicer 2.5.59 on 2023-08-01 at 16:05:57 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; object:{"name":"Shape-Box","id":"Shape-Box id:0 copy 0","object_center":[150.000000,150.000000,0.000000],"boundingbox_center":[150.000000,150.000000,0.100000],"boundingbox_size":[10.000000,10.000000,0.200000]}
; Total objects to print: 1
M486 T1
; plater:{"center":[150.000000,150.000000,0.000000],"boundingbox_center":[150.000000,150.000000,0.100000],"boundingbox_size":[10.000000,10.000000,0.200000]}

M201 X1000 Y1000 Z500 E5000 ; sets maximum accelerations, mm/sec^2
M203 X150 Y150 Z12 E120 ; sets maximum feedrates, mm / sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X5.00 Y5.00 Z0.40 E1.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
;TYPE:Custom
; custom gcode: start_gcode
; Initial setups
G90 ; use absolute coordinates
M83 ; extruder relative mode
M220 S100 ; reset speed factor to 100%
M221 S100 ; reset extrusion rate to 100%

; Set the heating
M190 S55 ; wait for bed to heat up
M104 S215 ; start nozzle heating but don't wait

; Home
G1 Z3 F3000 ; move z up little to prevent scratching of surface
G28 ; home all axes
G1 X3 Y3 F5000 ; move to corner of the bed to avoid ooze over centre

; Wait for final heating
M109 S215 ; wait for the nozzle to heat up
M190 S55 ; wait for the bed to heat up

; Return to prime position, Prime line routine
G92 E0 ; Reset Extruder
G1 Z3 F3000 ; move z up little to prevent scratching of surface
G1 X10 Y.5 Z0.25 F5000.0 ; Move to start position
G1 X100 Y.5 Z0.25 F1500.0 E15 ; Draw the first line
G1 X100 Y.2 Z0.25 F5000.0 ; Move to side a little
G1 X10 Y.2 Z0.25 F1500.0 E30 ; Draw the second line
G92 E0 ; Reset Extruder
M221 S95
; custom gcode end: start_gcode
M107 ; disable fan
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; custom gcode: start_filament_gcode
; Filament gcode
; custom gcode end: start_filament_gcode
;_TOOLCHANGE 0
M107 ; disable fan
;LAYER_CHANGE
;Z:0.3
;HEIGHT:0.3
; custom gcode: before_layer_gcode
;BEFORE_LAYER_CHANGE
;0.3
G92 E0
; custom gcode end: before_layer_gcode

G1 E-0.9 F2100 ; retract
G1 Z0.3 F7800 ; move to next layer (0)
; custom gcode: layer_gcode
;AFTER_LAYER_CHANGE
;0.3
; custom gcode end: layer_gcode

; printing object Shape-Box id:0 copy 0
M486 S0
M204 S500 ; adjust acceleration
G1 X145.21 Y145.21 ; move to first perimeter point
G1 E0.9 F2100 ; unretract
;TYPE:External perimeter
;WIDTH:0.42
G1 F720
G1 X154.79 Y145.21 E0.44616 ; perimeter
G1 X154.79 Y154.79 E0.44616 ; perimeter
G1 X145.21 Y154.79 E0.44616 ; perimeter
G1 X145.21 Y145.27 E0.44337 ; perimeter
;WIPE_START
M204 S1000 ; adjust acceleration
G1 X145.556 Y145.41 F7800 ; move inwards before travel
;WIPE_END
;WIPE_START
G1 F6240
M204 S500 ; adjust acceleration
G1 X148.231 Y145.41 E-0.855 ; wipe and retract
;WIPE_END
G1 E-0.045 F2100 ; retract
G1 X153.964 Y145.317 F7800 ; move to first Solid infill point
G1 E0.9 F2100 ; unretract
;TYPE:Solid infill
;WIDTH:0.422544
G1 F720
G1 X154.53 Y145.883 E0.0375 ; Solid infill
G1 X154.53 Y146.386 E0.02356 ; Solid infill
G1 X153.614 Y145.47 E0.0607 ; Solid infill
G1 X153.112 Y145.47 E0.02356 ; Solid infill
G1 X154.53 Y146.888 E0.09402 ; Solid infill
G1 X154.53 Y147.391 E0.02356 ; Solid infill
G1 X152.609 Y145.47 E0.12734 ; Solid infill
G1 X152.106 Y145.47 E0.02356 ; Solid infill
G1 X154.53 Y147.894 E0.16067 ; Solid infill
G1 X154.53 Y148.397 E0.02356 ; Solid infill
G1 X151.603 Y145.47 E0.19399 ; Solid infill
G1 X151.1 Y145.47 E0.02356 ; Solid infill
G1 X154.53 Y148.9 E0.22732 ; Solid infill
G1 X154.53 Y149.403 E0.02356 ; Solid infill
G1 X150.597 Y145.47 E0.26064 ; Solid infill
G1 X150.094 Y145.47 E0.02356 ; Solid infill
G1 X154.53 Y149.906 E0.29397 ; Solid infill
G1 X154.53 Y150.409 E0.02356 ; Solid infill
G1 X149.591 Y145.47 E0.32729 ; Solid infill
G1 X149.088 Y145.47 E0.02356 ; Solid infill
G1 X154.53 Y150.912 E0.36062 ; Solid infill
G1 X154.53 Y151.415 E0.02356 ; Solid infill
G1 X148.585 Y145.47 E0.39394 ; Solid infill
G1 X148.082 Y145.47 E0.02356 ; Solid infill
G1 X154.53 Y151.918 E0.42727 ; Solid infill
G1 X154.53 Y152.421 E0.02356 ; Solid infill
G1 X147.579 Y145.47 E0.46059 ; Solid infill
G1 X147.076 Y145.47 E0.02356 ; Solid infill
G1 X154.53 Y152.924 E0.49392 ; Solid infill
G1 X154.53 Y153.426 E0.02356 ; Solid infill
G1 X146.574 Y145.47 E0.52724 ; Solid infill
G1 X146.071 Y145.47 E0.02356 ; Solid infill
G1 X154.53 Y153.929 E0.56057 ; Solid infill
G1 X154.53 Y154.432 E0.02356 ; Solid infill
G1 X145.568 Y145.47 E0.59389 ; Solid infill
G1 X145.47 Y145.47 E0.0046 ; Solid infill
G1 X145.47 Y145.874 E0.01897 ; Solid infill
G1 X154.126 Y154.53 E0.57357 ; Solid infill
G1 X153.623 Y154.53 E0.02356 ; Solid infill
G1 X145.47 Y146.377 E0.54025 ; Solid infill
G1 X145.47 Y146.88 E0.02356 ; Solid infill
G1 X153.12 Y154.53 E0.50692 ; Solid infill
G1 X152.617 Y154.53 E0.02356 ; Solid infill
G1 X145.47 Y147.383 E0.4736 ; Solid infill
G1 X145.47 Y147.886 E0.02356 ; Solid infill
G1 X152.114 Y154.53 E0.44027 ; Solid infill
G1 X151.611 Y154.53 E0.02356 ; Solid infill
G1 X145.47 Y148.389 E0.40695 ; Solid infill
G1 X145.47 Y148.892 E0.02356 ; Solid infill
G1 X151.108 Y154.53 E0.37362 ; Solid infill
G1 X150.605 Y154.53 E0.02356 ; Solid infill
G1 X145.47 Y149.395 E0.3403 ; Solid infill
G1 X145.47 Y149.898 E0.02356 ; Solid infill
G1 X150.102 Y154.53 E0.30697 ; Solid infill
G1 X149.599 Y154.53 E0.02356 ; Solid infill
G1 X145.47 Y150.401 E0.27365 ; Solid infill
G1 X145.47 Y150.904 E0.02356 ; Solid infill
G1 X149.096 Y154.53 E0.24032 ; Solid infill
G1 X148.593 Y154.53 E0.02356 ; Solid infill
G1 X145.47 Y151.407 E0.207 ; Solid infill
G1 X145.47 Y151.909 E0.02356 ; Solid infill
G1 X148.091 Y154.53 E0.17367 ; Solid infill
G1 X147.588 Y154.53 E0.02356 ; Solid infill
G1 X145.47 Y152.412 E0.14035 ; Solid infill
G1 X145.47 Y152.915 E0.02356 ; Solid infill
G1 X147.085 Y154.53 E0.10702 ; Solid infill
G1 X146.582 Y154.53 E0.02356 ; Solid infill
G1 X145.47 Y153.418 E0.0737 ; Solid infill
G1 X145.47 Y153.921 E0.02356 ; Solid infill
G1 X146.079 Y154.53 E0.04037 ; Solid infill
G1 X145.576 Y154.53 E0.02356 ; Solid infill
G1 X145.317 Y154.271 E0.01718 ; Solid infill
;WIPE_START
G1 F6240;_WIPE
M204 S1000 ; adjust acceleration
G1 X145.576 Y154.53 E-0.11724 ; wipe and retract
G1 F6240;_WIPE
G1 X146.079 Y154.53 E-0.16079 ; wipe and retract
G1 F6240;_WIPE
G1 X145.47 Y153.921 E-0.27549 ; wipe and retract
G1 F6240;_WIPE
G1 X145.47 Y153.418 E-0.16079 ; wipe and retract
G1 F6240;_WIPE
G1 X145.781 Y153.729 E-0.1407 ; wipe and retract
;WIPE_END
G1 E-0.045 F2100 ; retract
; stop printing object Shape-Box id:0 copy 0
M486 S-1
M107 ; disable fan
;TYPE:Custom
; custom gcode: end_filament_gcode
; Filament-specific end gcode 
;END gcode for filament
; custom gcode end: end_filament_gcode
; custom gcode: end_gcode
G4 ; wait
G92 E0 ; prepare to retract
G1 E-0.5 F3000; retract to avoid stringing

; Anti-stringing end wiggle
G91 ; use relative coordinates
G1 X1 Y1 F1200

; Raise nozzle and present bed
G1 Z120.3 ; Move print head up
G90 ; use absolute coordinates

; Reset print setting overrides
M200 D0 ; disable volumetric e
M220 S100 ; reset speed factor to 100%
M221 S100 ; reset extrusion rate to 100%

; Shut down printer
M106 S0 ; turn-off fan
M104 S0 ; turn-off hotend
M140 S0 ; turn-off bed
M150 P0 ; turn off led
M85 S0 ; deactivate idle timeout
M84 ; disable motors
; custom gcode end: end_gcode
; filament used [mm] = 13.44
; filament used [cm3] = 0.03
; filament used [g] = 0.04
; filament cost = 0.00
; total filament used [g] = 0.04
; total filament cost = 0.00
; total layers count = 1
; estimated printing time (normal mode) = 1m 5s

; SuperSlicer_config = begin
; allow_empty_layers = 0
; arc_fitting = 0
; arc_fitting_tolerance = 5%
; avoid_crossing_not_first_layer = 1
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,300x0,300x300,0x300
; bed_temperature = 55
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 1.2
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_fill_pattern = rectilinear
; bridge_flow_ratio = 78%
; bridge_internal_acceleration = 0
; bridge_internal_fan_speed = -1
; bridge_overlap = 90%
; bridge_overlap_min = 80%
; bridge_speed = 20
; bridge_speed_internal = 150%
; bridge_type = nozzle
; bridged_infill_margin = 200%
; brim_acceleration = 0
; brim_ears = 0
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_ears_pattern = concentric
; brim_inside_holes = 0
; brim_per_object = 0
; brim_separation = 0
; brim_speed = 50%
; brim_width = 0
; brim_width_interior = 0
; chamber_temperature = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_model=~/(X1|Genius|Hornet).*/ and nozzle_diameter[0]==0.4";printer_notes=~/.*PRINTER_VENDOR_Artillery.*/
; complete_objects = 1
; complete_objects_one_skirt = 0
; complete_objects_sort = object
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; curve_smoothing_angle_concave = 0
; curve_smoothing_angle_convex = 0
; curve_smoothing_cutoff_dist = 2
; curve_smoothing_precision = 0
; default_acceleration = 1000
; default_filament_profile = "Generic PLA @Artillery"
; default_print_profile = 0.20mm NORMAL @Artillery
; default_speed = 100
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = G4 ; wait\nG92 E0 ; prepare to retract\nG1 E-0.5 F3000; retract to avoid stringing\n\n; Anti-stringing end wiggle\nG91 ; use relative coordinates\nG1 X1 Y1 F1200\n\n; Raise nozzle and present bed\n{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+120, max_print_height)}{endif} ; Move print head up\nG90 ; use absolute coordinates\n\n; Reset print setting overrides\nM200 D0 ; disable volumetric e\nM220 S100 ; reset speed factor to 100%\nM221 S100 ; reset extrusion rate to 100%\n\n; Shut down printer\nM106 S0 ; turn-off fan\nM104 S0 ; turn-off hotend\nM140 S0 ; turn-off bed\nM150 P0 ; turn off led\nM85 S0 ; deactivate idle timeout\nM84 ; disable motors\n
; enforce_full_fill_volume = 1
; enforce_retract_first_layer = 1
; ensure_vertical_shell_thickness = 0
; exact_last_layer_height = 0
; external_infill_margin = 150%
; external_perimeter_acceleration = 0
; external_perimeter_cut_corners = 0%
; external_perimeter_extrusion_spacing = 
; external_perimeter_extrusion_width = 0.45
; external_perimeter_fan_speed = -1
; external_perimeter_overlap = 100%
; external_perimeter_speed = 25
; external_perimeters_first = 0
; external_perimeters_hole = 1
; external_perimeters_nothole = 1
; external_perimeters_vase = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_odd_layers = 0
; extra_perimeters_overhangs = 0
; extruder_clearance_height = 25
; extruder_clearance_radius = 45
; extruder_colour = #F4FFFB
; extruder_fan_offset = 0%
; extruder_offset = 0x0
; extruder_temperature_offset = 0
; extrusion_axis = E
; extrusion_multiplier = 1.05
; extrusion_spacing = 
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; fan_kickstart = 0
; fan_percentage = 0
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; feature_gcode = 
; filament_colour = #428AF5
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cooling_zone_pause = 0
; filament_cost = 28
; filament_custom_variables = ""
; filament_density = 1.24
; filament_diameter = 1.75
; filament_dip_extraction_speed = 70
; filament_dip_insertion_speed = 33
; filament_enable_toolchange_part_fan = 0
; filament_enable_toolchange_temp = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_overlap = 100%
; filament_max_speed = 0
; filament_max_volumetric_speed = 15
; filament_max_wipe_tower_speed = 0
; filament_melt_zone_pause = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Generic PLA @Artillery - ERYONE White"
; filament_shrink = 100%
; filament_skinnydip_distance = 31
; filament_soluble = 0
; filament_spool_weight = 1000
; filament_toolchange_delay = 0
; filament_toolchange_part_fan_speed = 50
; filament_toolchange_temp = 200
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_use_fast_skinnydip = 0
; filament_use_skinnydip = 0
; filament_vendor = Generic
; filament_wipe_advanced_pigment = 0.5
; fill_angle = 45
; fill_angle_increment = 0
; fill_density = 15%
; fill_pattern = adaptivecubic
; fill_smooth_distribution = 10%
; fill_smooth_width = 50%
; fill_top_flow_ratio = 100%
; first_layer_acceleration = 500
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 55
; first_layer_extrusion_spacing = 
; first_layer_extrusion_width = 0.42
; first_layer_flow_ratio = 100%
; first_layer_height = 0.3
; first_layer_infill_speed = 0
; first_layer_min_speed = 0
; first_layer_size_compensation = 0
; first_layer_size_compensation_layers = 1
; first_layer_speed = 12
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 3
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_acceleration = 0
; gap_fill_enabled = 1
; gap_fill_extension = 0
; gap_fill_flow_match_perimeter = 0%
; gap_fill_last = 0
; gap_fill_max_width = 0
; gap_fill_min_area = 100%
; gap_fill_min_length = 0
; gap_fill_min_width = 0
; gap_fill_overlap = 100%
; gap_fill_speed = 30
; gcode_comments = 1
; gcode_filename_illegal_char = [<>:"/\\\\|?*]
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_precision_e = 5
; gcode_precision_xyz = 3
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; hole_size_compensation = 0
; hole_size_threshold = 100
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_connection = connected
; infill_connection_bottom = connected
; infill_connection_bridge = connected
; infill_connection_solid = connected
; infill_connection_top = connected
; infill_dense = 0
; infill_dense_algo = autoenlarged
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_spacing = 
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 50
; inherits_cummulative = "0.20mm NORMAL @Artillery";"Generic PLA @Artillery";"Artillery Sidewinder X1"
; init_z_rotate = 0
; interface_shells = 0
; ironing = 0
; ironing_acceleration = 0
; ironing_angle = -1
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; lift_min = 0
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 500,1000
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 150,100
; machine_max_feedrate_y = 150,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 1.5,1.5
; machine_max_jerk_x = 5,8
; machine_max_jerk_y = 5,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_gcode_per_second = 1500
; max_layer_height = 0.32
; max_print_height = 400
; max_print_speed = 150
; max_speed_reduction = 90%
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; milling_after_z = 200%
; milling_extra_size = 150%
; milling_post_process = 0
; milling_speed = 30
; milling_toolchange_end_gcode = 
; milling_toolchange_start_gcode = 
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_length = 0.035
; min_print_speed = 15
; min_skirt_length = 4
; min_width_top_surface = 100%
; mmu_segmented_region_max_width = 0
; model_precision = 0.0001
; no_perimeter_unsupported_algo = none
; notes = 
; nozzle_diameter = 0.4
; only_one_perimeter_first_layer = 0
; only_one_perimeter_top = 1
; only_one_perimeter_top_other_algo = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; over_bridge_flow_ratio = 100%
; overhangs_acceleration = 0
; overhangs_reverse = 0
; overhangs_reverse_threshold = 250%
; overhangs_speed = 100%
; overhangs_speed_enforce = 0
; overhangs_width = 75%
; overhangs_width_speed = 50%
; parking_pos_retraction = 92
; pause_print_gcode = 
; perimeter_acceleration = 800
; perimeter_bonding = 0%
; perimeter_extruder = 1
; perimeter_extrusion_spacing = 
; perimeter_extrusion_width = 0
; perimeter_generator = arachne
; perimeter_loop = 0
; perimeter_loop_seam = rear
; perimeter_overlap = 100%
; perimeter_round_corners = 0
; perimeter_speed = 45
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; print_custom_variables = 
; print_extrusion_multiplier = 100%
; print_retract_length = -1
; print_retract_lift = -1
; print_settings_id = 0.20mm NORMAL @Artillery - Custom
; print_temperature = 0
; printer_custom_variables = 
; printer_model = X1
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_Artillery\nPRINTER_MODEL_X1
; printer_settings_id = Artillery Sidewinder X1 - LH 0.2mm
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_interface_layer_height = 0
; raft_layer_height = 0
; raft_layers = 0
; remaining_times = 0
; remaining_times_type = m73
; resolution = 0
; resolution_internal = 0.1
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.9
; retract_length_toolchange = 4
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 380
; retract_lift_first_layer = 0
; retract_lift_top = "All surfaces"
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_angle_cost = 60%
; seam_gap = 15%
; seam_notch_all = 0
; seam_notch_angle = 250
; seam_notch_inner = 0
; seam_notch_outer = 0
; seam_position = cost
; seam_travel_cost = 100%
; seam_visibility = 1
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_brim = 0
; skirt_distance = 6
; skirt_distance_from_brim = 1
; skirt_extrusion_width = 130%
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_max_length = 20
; small_perimeter_min_length = 6
; small_perimeter_speed = 25
; solid_fill_pattern = rectilineargapfill
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_spacing = 
; solid_infill_extrusion_width = 0.45
; solid_infill_overlap = 100%
; solid_infill_speed = 50
; solid_over_perimeters = 2
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = ; Initial setups\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM220 S100 ; reset speed factor to 100%\nM221 S100 ; reset extrusion rate to 100%\n\n; Set the heating\nM190 S[first_layer_bed_temperature] ; wait for bed to heat up\nM104 S[first_layer_temperature] ; start nozzle heating but don't wait\n\n; Home\nG1 Z3 F3000 ; move z up little to prevent scratching of surface\nG28 ; home all axes\nG1 X3 Y3 F5000 ; move to corner of the bed to avoid ooze over centre\n\n; Wait for final heating\nM109 S[first_layer_temperature] ; wait for the nozzle to heat up\nM190 S[first_layer_bed_temperature] ; wait for the bed to heat up\n\n; Return to prime position, Prime line routine\nG92 E0 ; Reset Extruder\nG1 Z3 F3000 ; move z up little to prevent scratching of surface\nG1 X10 Y.5 Z0.25 F5000.0 ; Move to start position\nG1 X100 Y.5 Z0.25 F1500.0 E15 ; Draw the first line\nG1 X100 Y.2 Z0.25 F5000.0 ; Move to side a little\nG1 X10 Y.2 Z0.25 F1500.0 E30 ; Draw the second line\nG92 E0 ; Reset Extruder\nM221 S{if layer_height<0.075}100{else}95{endif}
; start_gcode_manual = 0
; support_material = 0
; support_material_acceleration = 0
; support_material_angle = 0
; support_material_angle_height = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.15
; support_material_contact_distance_type = filament
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_acceleration = 0
; support_material_interface_angle = 90
; support_material_interface_angle_increment = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_fan_speed = -1
; support_material_interface_layer_height = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_layer_height = 0
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 215
; template_custom_gcode = 
; thin_perimeters = 80%
; thin_perimeters_all = 20%
; thin_walls = 1
; thin_walls_acceleration = 0
; thin_walls_merge = 1
; thin_walls_min_width = 33%
; thin_walls_overlap = 50%
; thin_walls_speed = 100%
; threads = 4
; thumbnails = 0x0,0x0
; thumbnails_color = #018aff
; thumbnails_custom_color = 0
; thumbnails_end_file = 0
; thumbnails_format = PNG
; thumbnails_with_bed = 1
; time_cost = 0
; time_estimation_compensation = 100%
; time_start_gcode = 20
; time_toolchange = 30
; tool_name = ""
; toolchange_gcode = 
; top_fan_speed = -1
; top_fill_pattern = monotonic
; top_infill_extrusion_spacing = 
; top_infill_extrusion_width = 0.4
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 30
; top_solid_layers = 5
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_deceleration_use_target = 1
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_advanced = 0
; wipe_advanced_algo = linear
; wipe_advanced_multiplier = 60
; wipe_advanced_nozzle_melted_volume = 120
; wipe_extra_perimeter = 0
; wipe_inside_depth = 50%
; wipe_inside_end = 1
; wipe_inside_start = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_only_crossing = 1
; wipe_speed = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_inner_size_compensation = 0
; xy_size_compensation = 0
; z_offset = 0
; z_step = 0.005
; SuperSlicer_config = end
